# fly.toml app configuration file generated for discord-ml-bot on 2023-08-30T12:10:10+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "discord-ml-bot"
primary_region = "sin"

[build]
[env]
DECT_API = "https://an-bot-obj-dect.fly.dev/obj-dect"
NTS_API = "https://an-bot-nts.fly.dev/combine-NTS"
[[services]]
protocol = "tcp"
internal_port = 8080
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 1
