version: "3.7"

services:
  detection:
    build:  ./services/detection
    restart: always
    ports:
      - "8080:5000"
    volumes:
      - ./services/detection/:/app
      - ./services/detection/main.py:/app/app.py
      - ./services/detection/main.py:/app/main.py
      - ./services/detection/yolov5x.ppt:/app/yolov5x.ppt
    environment:
      FLASK_APP: "${FLASK_APP}"
      API_KEY: "${API_KEY}"
      AUTH_DOMAIN: "${AUTH_DOMAIN}"
      PROJECT_ID: "${PROJECT_ID}"
      STORAGE_BUCKET: "${STORAGE_BUCKET}"
      MESSAGING_SENDER_ID: "${MESSAGING_SENDER_ID}"
      APP_ID: "${APP_ID}"
      MEASUREMENT_ID: "${MEASUREMENT_ID}"

  disord-bot:
    build:  ./services/discord-bot
    restart: always
    volumes:
      - ./services/discord-bot/:/app
      - ./services/discord-bot/main.py:/app/main.py
    environment:
      PREFIX: "${PREFIX}"
      TOKEN: "${TOKEN}"
     